- name: OBS Studio
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_popos: "{{ not is_mac and 'Pop!_OS' in hostvars[inventory_hostname].ansible_facts.lsb.description }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Add APT package source (Ubuntu)
      become: yes
      apt_repository:
        repo: ppa:obsproject/obs-studio
      register: apt_repository
      when: is_ubuntu and not is_wsl and not is_popos

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install OBS Studio (Linux)
      become: yes
      apt:
        package: obs-studio
      when: is_ubuntu and not is_wsl

    # macOS

    - name: Install OBS Studio (macOS)
      homebrew_cask:
        name: obs
      when: is_mac
