- name: Sway (wayland window manager)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}
    # Linux

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      register: apt_update
      retries: 5
      until: apt_update is success
      when: not is_mac

    - name: Install packages
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - sway
        - waybar
        - swaylock
        - swayidle
      when: not is_mac and not is_wsl
