- name: displaylink
  hosts: 127.0.0.1
  connection: local

  vars:
    ubuntu_focal_installer_version: 5.6.0-59.176
    download_url: "https://synaptics.com/sites/default/files/exe_files/2022-05/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.6-EXE.zip"
    is_ubuntu_focal: "{{ ansible_distribution_release == 'focal' }}"

  tasks:
    # Linux
    - name: Install DisplayLink requirements (Linux)
      become: yes
      apt:
        pkg:
        - dkms
        - libdrm-dev
      when: is_ubuntu_focal

    - name: Unzip  installer archive (Linux)
      # become: yes
      unarchive:
        src: "{{download_url}}"
        dest: /tmp
        remote_src: yes
        # creates: /tmp/displaylink-driver-{{ubuntu_focal_installer_version}}.run
      register: displaylink_download_linux
      when: is_ubuntu_focal

    - name: Make script executable
      file:
        path: /tmp/displaylink-driver-{{ubuntu_focal_installer_version}}.run
        mode: "u=rx"
      when: is_ubuntu_focal and displaylink_download_linux

    - name: Run installer as sudoer
      become: yes
      shell:
        /tmp/displaylink-driver-{{ubuntu_focal_installer_version}}.run
      when: is_ubuntu_focal and displaylink_download_linux
