- name: DisplayLink
  hosts: 127.0.0.1
  connection: local

  vars:
    ubuntu_focal_installer_fileid: 1576
    ubuntu_focal_installer_version: 5.3.1.34
    is_ubuntu_focal: "{{ ansible_distribution_release == 'focal' }}"

  tasks:
    # Linux

    - name: Fetch installer archive (Linux)
      # become: yes
      unarchive:
        src: https://www.displaylink.com/downloads/file?id={{ubuntu_focal_installer_fileid}}
        dest: /tmp/displaylink-{{ubuntu_focal_installer_version}}
        remote_src: yes
        creates: /tmp/displaylink-{{ubuntu_focal_installer_version}}
      register: displaylink_download_linux
      when: is_ubuntu_focal

    - name: Run installer as sudoer
      become: yes
      shell: /tmp/displaylink-{{ubuntu_focal_installer_version}}/displaylink-driver-{{ubuntu_focal_installer_version}}.run
      when: is_ubuntu_focal
