- import_playbook: ../rust-lang/core.yaml    # diffr is installed with Rust's cargo package manager

- name: git (customization)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_debian: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'  or ansible_distribution == 'Debian' }}"

  tasks:
    - name: Install diffr
      command: ~/.cargo/bin/cargo install diffr
      args:
        creates: ~/.cargo/bin/diffr

    - name: Install difftastic
      command: ~/.cargo/bin/cargo install difftastic
      args:
        creates: ~/.cargo/bin/difft

    # download & install delta
    - name: Determine delta latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/dandavison/delta/releases/latest | jq -r .name"
        warn: false
      register: delta_version
      when: is_debian

    - name: Install latest delta (Linux amd64)
      become: yes
      apt:
        deb: https://github.com/dandavison/delta/releases/download/{{ delta_version.stdout }}/git-delta_{{ delta_version.stdout }}_amd64.deb
      register: delta_download_linux
      when: is_debian

    # download & install hwatch
    - name: Determine hwatch latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/blacknon/hwatch/releases/latest | jq -r .name"
        warn: false
      register: hwatch_version
      when: is_debian

    - name: Install latest hwatch (Linux amd64)
      become: yes
      apt:
        deb: https://github.com/blacknon/hwatch/releases/download/{{ hwatch_version.stdout }}/hwatch-{{ hwatch_version.stdout }}.x86_64-unknown-linux-musl.deb
      register: hwatch_download_linux
      when: is_debian

    - name: Download git-completion.bash
      get_url:
        url:  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
        dest: ~/.git-completion.bash

    - name: Add bash completion for git
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: git-completion.bash"
        block: |
          if [ -f ~/.git-completion.bash ]; then
            . ~/.git-completion.bash
          fi

    - name: Ensure ~/.config exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Create ~/.config/ripgrep
      copy:
        dest: ~/.config/ripgrep
        mode: 0755
        content: |
          --hidden

    - name: Set ripgrep configuration path
      lineinfile:
        path: ~/.bashrc
        line: export RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep
