- name: Google Earth
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_debian: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'  or ansible_distribution == 'Debian' }}"
    EARTH_VERSION: "7.3.3"

  tasks:
    # Linux

    - name: Install Google Earth Pro
      become: yes
      apt:
        deb: https://dl.google.com/dl/linux/direct/google-earth-pro-stable_{{ EARTH_VERSION }}_amd64.deb
      when: is_debian
