- name: image-processing
  hosts: 127.0.0.1
  connection: local

  vars:
    is_debian_stretch: "{{ ansible_distribution_release == 'stretch' }}"
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"

  tasks:
    # Linux
    - name: Install APT packages
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - gimp
      when: not is_mac
