- name: VIM
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Install VIM (Linux)
      become: yes
      apt:
        package: vim
      when: not is_mac

    - name: Install Fuzzy Finder (Linux)
      become: yes
      apt:
        package: fzf
      when: not is_mac

    - name: Add APT package source (Ubuntu)
      become: yes
      apt_repository:
        repo: ppa:neovim-ppa/unstable
      register: apt_repository
      when: is_ubuntu and not is_wsl

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install NEOVIM unstable (Linux)
      become: yes
      apt:
        package: neovim
      when: is_ubuntu and not is_wsl


    # macOS

    - name: Install VIM (macOS)
      homebrew_cask:
        name: vim
      when: is_mac
