- name: Developer tools
  hosts: 127.0.0.1
  connection: local

  vars:
    is_debian: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'  or ansible_distribution == 'Debian' }}"
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    SOPS_VERSION: "3.8.1"
    GLOW_VERSION: "1.5.1"
    ZOXIDE_VERSION: "0.9.2"

  tasks:
    # Linux
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Install SOPS from github releases
      become: yes
      apt:
        deb: https://github.com/getsops/sops/releases/download/v{{SOPS_VERSION}}/sops_{{SOPS_VERSION}}_amd64.deb
      when: is_debian

    - name: Install Glow (TUI markdown reader)
      become: yes
      apt:
        deb: https://github.com/charmbracelet/glow/releases/download/v{{GLOW_VERSION}}/glow_{{GLOW_VERSION}}_amd64.deb
      when: is_debian

    - name: Install FD (find alternative)
      become: yes
      apt:
        package: fd-find
      when: is_debian

    - name: Install latest zoxide (Linux)
      become: yes
      apt:
        deb: https://github.com/ajeetdsouza/zoxide/releases/download/v{{ZOXIDE_VERSION}}/zoxide_{{ZOXIDE_VERSION}}_amd64.deb
      register: zoxide_download_linux
      when: not is_mac
