- name: Developer tools (GUI)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"
    is_debian_family: "{{ ansible_os_family == 'Debian' }}"
    is_debian: "{{ ansible_distribution == 'Debian' }}"
    DBEAVER_INSTALL: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
    ADS_INSTALL: https://azuredatastudio-update.azurewebsites.net/latest/linux-deb-x64/stable

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    # DBeaver
    - name: Install DBeaver SQL client from provided debian package
      become: yes
      apt:
        deb: "{{ DBEAVER_INSTALL }}"
      when: is_debian_family and not is_wsl

    # Azure Data Studio
    - name: Install Azure Data Studio
      become: yes
      apt:
        deb: "{{ ADS_INSTALL }}"
        state: present
        autoremove: true
      register: azuredatastudio
      # when: azuredatastudio_deps.changed and is_debian_family and not is_wsl

    - name: Install Wireshark
      become: yes
      apt:
        package: wireshark
      when: is_ubuntu and not is_wsl
