- name: QR Code
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"
    QRTERM_VERSION: 3.1.1

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}
    # Linux
    - name: Install APT packages
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - zbar-tools
      when: not is_mac and not is_wsl

    - name: qrterminal
      unarchive:
        src: https://github.com/mdp/qrterminal/releases/download/v{{QRTERM_VERSION}}/qrterminal_Linux_x86_64.tar.gz
        dest: /tmp
        remote_src: yes
        creates: /tmp/qrterminal/qrterminal
      register: qrterminal_unarc
    - name: Move qrterminal to ~/bin
      copy:
        dest: ~/bin/qrterminal
        src: /tmp/qrterminal
        mode: u+rx,g-wx,o-rwx
