- name: Power management
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Install LM sensors (Linux)
      become: yes
      apt:
        package: lm-sensors
      when: is_ubuntu and not is_wsl

    - name: Install Fan control (Linux)
      become: yes
      apt:
        package: fancontrol
      when: is_ubuntu and not is_wsl

    - name: Install TLP (Linux)
      become: yes
      apt:
        package: tlp
      when: is_ubuntu and not is_wsl

    - name: Install smartmontools (Linux)
      become: yes
      apt:
        package: smartmontools
      when: is_ubuntu and not is_wsl

    - name: Install cpufreq tools (Linux)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - indicator-cpufreq
        - cpufrequtils
      when: is_ubuntu and not is_wsl
