- name: Discord app
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_debian: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'  or ansible_distribution == 'Debian' }}"
    discord_package_url: "https://discordapp.com/api/download?platform=linux&format=deb"

  tasks:
    # Linux

    - name: Install Discord app
      become: yes
      apt:
        deb: "{{ discord_package_url }}"
      when: is_debian
