- name: VS Code (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure ~/.config folder exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Install VS Live Share dependencies
      become: yes
      apt:
        name: "{{ item }}"
      loop:
        - openssl
        - gnome-keyring
        - libsecret-1-0
        - desktop-file-utils
        - x11-utils

    - name: Install VS Code extensions
      command: ./invoke-code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - ms-dotnettools.vscode-dotnet-pack
        - ms-dotnettools.vscode-dotnet-runtime
        - MS-vsliveshare.vsliveshare
        - visualstudioexptteam.vscodeintellicode
        - nicoespeon.abracadabra
        - ms-dotnettools.csharp
        - sohamkamani.code-eol
        - ryanluker.vscode-coverage-gutters
        - ms-vscode-remote.remote-containers
        - dbaeumer.vscode-eslint
        - mhutchie.git-graph
        - GitHub.vscode-pull-request-github
        - GitHub.remotehub
        - eamodio.gitlens
        - hashicorp.terraform
        - alfonsogarciacaro.vscode-template-fsharp-highlight
        - oderwat.indent-rainbow
        - Ionide.Ionide-fsharp
        - Ionide.Ionide-Paket
        - kavod-io.vscode-jest-test-adapter
        - ms-dotnettools.dotnet-interactive-vscode
        - esbenp.prettier-vscode
        - ms-python.python
        - redhat.vscode-yaml

    - name: Ensure ~/.config folder exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Link '~/Library/Application Support/Code' to '~/.config/Code' (macOS)
      file:
        path: ~/.config/Code
        src: ~/Library/Application Support/Code
        state: link
      when: is_mac

#    - name: Override default VS Code preferences
#      copy:
#        src: settings.json
#        dest: ~/.config/Code/User/settings.json
#
#    - name: Override default VS Code key bindings
#      copy:
#        src: keybindings.json
#        dest: ~/.config/Code/User/keybindings.json
