- name: VS Code (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure ~/.config folder exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Install VS Live Share dependencies
      become: yes
      apt:
        name: "{{ item }}"
      loop:
        - openssl
        - gnome-keyring
        - libsecret-1-0
        - desktop-file-utils
        - x11-utils

    - name: Install VS Code extensions
      command: ./invoke-code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        #- amodio.toggle-excluded-files                    # Toggle Excluded Files
        - editorconfig.editorconfig                       # EditorConfig for VS Code
        - ms-vsliveshare.vsliveshare-pack                 # Live Share Extension Pack
        #- pkief.material-icon-theme                       # Material Icon Theme
        #- eamodio.toggle-excluded-files                   # Toggle Excluded Files
        #- pflannery.vscode-versionlens                    # Version Lens
        - visualstudioexptteam.vscodeintellicode          # Visual Studio IntelliCode

    - name: Ensure ~/.config folder exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Link '~/Library/Application Support/Code' to '~/.config/Code' (macOS)
      file:
        path: ~/.config/Code
        src: ~/Library/Application Support/Code
        state: link
      when: is_mac

#    - name: Override default VS Code preferences
#      copy:
#        src: settings.json
#        dest: ~/.config/Code/User/settings.json
#
#    - name: Override default VS Code key bindings
#      copy:
#        src: keybindings.json
#        dest: ~/.config/Code/User/keybindings.json
