- name: .NET (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code extensions
      command: ../vscode/invoke-code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - ms-dotnettools.csdevkit               # C# Dev Kit
        - formulahendry.dotnet-test-explorer    # .NET Core Test Explorer
        # - k--kato.docomment                     # C# XML Documentation Comments
        - ms-dotnettools.csharp                 # C#
        - ionide.ionide-fsharp
