- name: 1Password
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"
    is_debian_flavor: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' or ansible_distribution == 'Debian'}}"
    OP_VERSION: "v1.9.0"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Add 1Password APT package key
      become: yes
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
        keyring: /usr/share/keyrings/1password.gpg
      when: is_debian_flavor and not is_wsl

    - name: Add 1Password APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password.gpg] https://downloads.1password.com/linux/debian edge main
        filename: 1password
        update_cache: no
      register: apt_repository
      when: is_debian_flavor and not is_wsl

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install 1Password (Linux)
      become: yes
      apt:
        package: 1password
      when: is_debian_flavor and not is_wsl

#    -name: Install 1Password CLI (Linux)
      become: yes
      get_url:
        url: https://cache.agilebits.com/dist/1P/op/pkg/{{ OP_VERSION }}/op_linux_amd64_{{ OP_VERSION }}.zip
        dest: /usr/local/bin/op
        mode: 0755
      register: op_download_linux
      when: not is_mac

    # macOS

    - name: Install 1Password (macOS)
      homebrew_cask:
        name: 1password
      when: is_mac
