- name: printers
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_debian: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'  or ansible_distribution == 'Debian' }}"
    DRIVER_VERSION: "1.5.0-0"

  tasks:
    # Linux

    - name: Install LPR printer driver
      become: yes
      apt:
        deb: https://download.brother.com/welcome/dlf103241/mfcl8690cdwlpr-{{ DRIVER_VERSION}}.i386.deb
      when: is_debian

    - name: Install CUPSwrapper printer driver
      become: yes
      apt:
        deb: https://download.brother.com/welcome/dlf103250/mfcl8690cdwcupswrapper-{{ DRIVER_VERSION}}.i386.deb
      when: is_debian
